baseurl = "" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "Undecidable" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating
publishDir = "docs"

# Controls default theme and theme components
theme = [
  "fractal-forest",
  "after-dark"
]

enableRobotsTXT = true # Suggested, enable robots.txt file

pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "" # Suggested, controls default description meta
  author = "Sergio Prada" # Optional, controls author name display on posts
  hide_author = true # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  has_cookies = false # Optional, set true to disable cookie disclaimer
  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

